# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: quote_generator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  # every day
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set up environment
        env:
          PORT: ${{ secrets.PORT }}
          URL: ${{ secrets.URL }}
        run: |
          echo "PORT=$PORT" >> .env
          echo "URL=$URL" >> .env

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Run
        run: |
          go get "github.com/goccy/go-json"
          go get "github.com/joho/godotenv"
          go run ./main.go

      - name: Update README.md
        run: |
          git config --global user.email "kietnguyen17052001@gmail.com"
          git config --global user.name "ngdangkiet"
          timestamp=$(TZ=Asia/Ho_Chi_Minh date +"%Y-%m-%d %H:%M:%S %Z")
          git add .
          git commit -m "Updated README.md at $timestamp" || echo "No changes to commit"
          git push